export enum EErrorCode {
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID = 'AUTH_TOKEN_INVALID',
  AUTH_ACCOUNT_INACTIVE = 'AUTH_ACCOUNT_INACTIVE',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  DUPLICATE_RESOURCE = 'DUPLICATE_RESOURCE',
  WORKFLOW_INVALID_STATE = 'WORKFLOW_INVALID_STATE',
  INSUFFICIENT_STOCK = 'INSUFFICIENT_STOCK',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
